services:
  meowy:
    image: arasfon/meowy
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - MEOWY_ConnectionStrings__Main=Host=postgres;Database=meowy;Username=meowy;Password=change-me;
    volumes:
      - data-protection:/home/app/.aspnet/DataProtection-Keys
    depends_on:
      - postgres
  
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_DB=meowy
      - POSTGRES_USER=meowy
      - POSTGRES_PASSWORD=change-me
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  data-protection:
  db: